### PR TITLE
Facebook account linking feature

### PR DESCRIPTION
**Pull request by syshen**
Hi Guidone, not sure you accept any PR or not. 
I am using your works on my project, and I need some functionalities to support some features. So I am adding them myself. If you have any concern, kindly let me know.

### CODE REVIEW

**Comment by guidone** [comment]
@syshen Yes, I'd like to, the feature you're implementing is this right?

https://developers.facebook.com/docs/messenger-platform/webhook-reference/account-linking

Give me some time for a check and I'll merge, thanks for the contribution

Guido

**Comment by syshen** [comment]
@guidone yes, that is my commit. It enables the Facebook Account linking function. And I am also working on Line integration. Line is a very popular IM app in the east Asia.

**Comment by guidone** [comment]
@syshen Merged! Sorry for the delay and thank you for the contribution, I've added some basic unit testing

**Comment by guidone** [comment]
Hi @syshen, I've removed this node and added the functionality in the more generic `Button node` which supports login, logout, etc

**Pull request merged**
