### PR TITLE
fix alexa invalid response

### PR DESCRIPTION
**Pull request by subzero79**
This was the only way i could make chatbot work with alexa. 
Also looks like the directive node needs a lot of work, some of them don't chain properly with speech leaving sending response with no text.
Has this alexa node being properly tested lately?

### CODE REVIEW

**Comment by guidone** [comment]
Hi @subzero79 , I'm looking into this.
I've not been using Alexa for a while honestly.
Thanks for the contirbution

**Comment by guidone** [comment]
[Fix Amazon Alexa](https://trello.com/c/kTp6hiRe/29-fix-amazon-alexa)

**Comment by guidone** [comment]
Ok, I've found the problem, I'll close this PR in favour of #382.
In my example the directive node is chaining properly, can you give an example? (perhaps it will be fixed with the #382 )

**Comment by subzero79** [comment]
No problem. Just one thing reading the docs I don’t why it was decided that endsession should carry no text speech. It should allow text, as the docs in Amazon allow the payload to contain a text ending the session.

**Comment by guidone** [comment]
Ok, fixes to Alexa is in `0.18.7`, I've created another issue #383

**Pull request closed without merging**
